trigger: 
- main

pool: 
   vmImage: Ubuntu2204

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: javascript-entorno
    resourceType: virtualMachine
    resourceName: SandboxHost-638360319604750425
  strategy:
    runOnce:
      deploy:   
          steps:
          - script: echo "Hello world"