trigger: 
- main

pool: 
   vmImage: Ubuntu2204

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: javascript-entorno
   resourceName: SandboxHost-63836031960
   resourceType: virtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"